version: '3.3'
services:
  database:
    image: mysql:5.7
    container_name: market_mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'market'   
      MYSQL_USER: 'market_user'
      MYSQL_PASSWORD: 'market_pass'      
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './volumes/mysql:/var/lib/mysql'
      - "./lib/infra/database/create.sql:/docker-entrypoint-initdb.d/1.sql"